repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.0.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--target-version=py37]

ci:
  autoupdate_schedule: quarterly
